database:
  url_path: postgresql://fampay:password@localhost/fampay?sslmode=disable
  log_queries: true
  timeout_seconds: 30
  max_idle_conns: 10

server:
  port: 8080
  debug: true
  timeout_seconds: 30

youtube:
  YOUTUBE_API_KEY: <YOUTUBE_API_KEY>
